# Generated by Django 6.0.3 on 2026-06-07 10:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(help_text='Nama brand/vendor', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Logo brand (rekomendasi: PNG dengan background transparan)', null=True, upload_to='brands/logos/')),
                ('description', models.TextField(blank=True, help_text='Deskripsi detail tentang brand/vendor', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status persetujuan brand (pending, approved, rejected)', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Tanggal brand disetujui oleh admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal brand didaftar')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal brand terakhir diperbarui')),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', help_text='Admin yang menyetujui brand ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_brands', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.OneToOneField(db_column='user_id', help_text='User/vendor yang memiliki brand ini', on_delete=django.db.models.deletion.CASCADE, related_name='brand_vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.OneToOneField(db_column='user_id', help_text='User pemilik cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', help_text='Nama kategori produk (harus unik)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Deskripsi detail tentang kategori', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal kategori dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal kategori terakhir diperbarui')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['category_name'],
                'indexes': [models.Index(fields=['category_name'], name='categories_categor_283d4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(help_text='Kode unik order', max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='Tanggal dan waktu order dibuat')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', help_text='Status order', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total jumlah uang order', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('e_wallet', 'E-Wallet'), ('cash_on_delivery', 'Cash on Delivery')], help_text='Metode pembayaran', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Status pembayaran', max_length=20)),
                ('shipping_address', models.TextField(help_text='Alamat lengkap pengiriman')),
                ('receiver_name', models.CharField(help_text='Nama penerima barang', max_length=255)),
                ('phone', models.CharField(help_text='Nomor telepon penerima', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal order dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal order terakhir diperbarui')),
                ('brand_id', models.ForeignKey(db_column='brand_id', help_text='Brand/vendor penjual dalam order ini', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='master_products.brand')),
                ('user_id', models.ForeignKey(db_column='user_id', help_text='Customer yang melakukan pesanan', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Nama produk', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier untuk produk', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Deskripsi detail produk')),
                ('price', models.DecimalField(decimal_places=2, help_text='Harga jual produk', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, help_text='Jumlah stok produk yang tersedia', validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, help_text='Foto/gambar produk', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif produk (true = aktif, false = non-aktif)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal produk didaftarkan')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal produk terakhir diperbarui')),
                ('brand_id', models.ForeignKey(db_column='brand_id', help_text='Brand/vendor penjual produk', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='master_products.brand')),
                ('category_id', models.ForeignKey(db_column='category_id', help_text='Kategori produk', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master_products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Harga produk pada saat order', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.IntegerField(default=1, help_text='Jumlah produk yang dipesan', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal order item dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal order item terakhir diperbarui')),
                ('order_id', models.ForeignKey(db_column='order_id', help_text='Order yang memuat item ini', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master_products.order')),
                ('product_id', models.ForeignKey(db_column='product_id', help_text='Produk dalam order', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='master_products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=1, help_text='Jumlah produk dalam cart', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Harga produk pada saat ditambahkan ke cart', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal item ditambahkan ke cart')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal item di-update')),
                ('cart_id', models.ForeignKey(db_column='cart_id', help_text='Cart yang memuat item ini', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master_products.cart')),
                ('product_id', models.ForeignKey(db_column='product_id', help_text='Produk dalam cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='master_products.product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Rating produk (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Komentar atau review produk', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal review dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal review terakhir diperbarui')),
                ('product_id', models.ForeignKey(db_column='product_id', help_text='Produk yang di-review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='master_products.product')),
                ('user_id', models.ForeignKey(db_column='user_id', help_text='User yang memberikan review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(help_text='Nama Brand / Toko Resmi Elektronik', max_length=255)),
                ('nib', models.CharField(help_text='Nomor Induk Berusaha (NIB) atau Nomor KTP', max_length=100, unique=True)),
                ('category', models.CharField(help_text='Kategori utama elektronik yang dijual', max_length=100)),
                ('address', models.TextField(help_text='Alamat lengkap gudang distribusi (kota, provinsi, kode pos)')),
                ('description', models.TextField(help_text='Deskripsi latar belakang bisnis dan alasan bergabung')),
                ('status', models.CharField(choices=[('Pending', 'Menunggu Verifikasi'), ('Approved', 'Disetujui'), ('Rejected', 'Ditolak')], default='Pending', help_text='Status pengajuan vendor', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Catatan atau alasan penolakan dari Admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal pengajuan dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal pembaruan terakhir')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', help_text='User yang melakukan pengajuan (jika terdaftar)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Request',
                'verbose_name_plural': 'Vendor Requests',
                'db_table': 'vendor_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['status'], name='brands_status_28bd17_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['user_id'], name='brands_user_id_6a84ee_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['created_at'], name='brands_created_5b9afc_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user_id'], name='carts_user_id_b1c689_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_code'], name='orders_order_c_c94bae_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id'], name='orders_user_id_4e08b8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['brand_id'], name='orders_brand_i_065295_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_050188_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand_id'], name='products_brand_i_0d1950_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_id'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order_id'], name='order_items_order_i_26ad88_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_id'], name='order_items_product_a53db1_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart_id'], name='cart_items_cart_id_3caa7d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product_id'], name='cart_items_product_6a1de7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart_id', 'product_id')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product_id'], name='reviews_product_3516b2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user_id'], name='reviews_user_id_79db63_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rating_17e8a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product_id', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='vendorrequest',
            index=models.Index(fields=['status'], name='vendor_requ_status_8dec29_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorrequest',
            index=models.Index(fields=['-created_at'], name='vendor_requ_created_a2653b_idx'),
        ),
    ]
