# Generated by Django 6.0.3 on 2026-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_products', '0003_migrate_brandprofile_to_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Alasan pembatalan order (jika applicable)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Nomor resi dari kurir pengiriman', max_length=100, null=True),
        ),
    ]
