# Generated by Django 6.0.3 on 2026-06-23 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_products', '0004_order_cancel_reason_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Apakah produk sedang di-featured/promosi'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rating produk dari customer (0.00-5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Jumlah review yang diterima produk', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
