# Generated by Django 6.0.6 on 2026-06-24 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_products', '0005_product_is_featured_product_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text="Nama perangkat (contoh: 'Chrome on Windows', 'Safari on iPhone')", max_length=255)),
                ('ip_address', models.CharField(blank=True, help_text='Alamat IP perangkat saat login', max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Status session saat ini (aktif atau sudah logout)')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Waktu aktivitas terakhir di session ini')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal dan waktu session dibuat (saat login)')),
            ],
            options={
                'verbose_name': 'Login Session',
                'verbose_name_plural': 'Login Sessions',
                'db_table': 'login_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserTwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Status aktivasi Two-Factor Authentication')),
                ('secret_key', models.CharField(blank=True, help_text='Secret key untuk Time-based One-Time Password (TOTP)', max_length=255, null=True)),
                ('backup_codes', models.TextField(blank=True, help_text='Kode backup untuk akses emergency (simpan sebagai JSON)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal 2FA pertama kali diaktifkan')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal 2FA terakhir diperbarui')),
            ],
            options={
                'verbose_name': 'User Two-Factor Authentication',
                'verbose_name_plural': 'User Two-Factor Authentications',
                'db_table': 'user_two_factor',
            },
        ),
        migrations.RemoveIndex(
            model_name='vendorrequest',
            name='vendor_requ_created_a2653b_idx',
        ),
        migrations.AlterField(
            model_name='vendorrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Catatan dari admin untuk pengajuan ini', null=True),
        ),
        migrations.AlterField(
            model_name='vendorrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Tanggal pengajuan terakhir diperbarui'),
        ),
        migrations.AddIndex(
            model_name='vendorrequest',
            index=models.Index(fields=['user'], name='vendor_requ_user_id_fe3230_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorrequest',
            index=models.Index(fields=['created_at'], name='vendor_requ_created_a4ceb6_idx'),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='User yang memiliki session ini', on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertwofactor',
            name='user',
            field=models.OneToOneField(db_column='user_id', help_text='User yang menggunakan 2FA', on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user'], name='login_sessi_user_id_b0ecb7_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['is_active'], name='login_sessi_is_acti_dfef5c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['created_at'], name='login_sessi_created_c2c011_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['last_activity'], name='login_sessi_last_ac_900d44_idx'),
        ),
        migrations.AddIndex(
            model_name='usertwofactor',
            index=models.Index(fields=['user'], name='user_two_fa_user_id_9ab027_idx'),
        ),
        migrations.AddIndex(
            model_name='usertwofactor',
            index=models.Index(fields=['is_enabled'], name='user_two_fa_is_enab_365837_idx'),
        ),
    ]
