# Generated by Django 6.0.5 on 2026-06-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_products', '0007_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='email',
            field=models.EmailField(default='', help_text='Alamat email pengaju yang akan digunakan untuk notifikasi dan verifikasi', max_length=255),
            preserve_default=False,
        ),
    ]
