# Generated by Django 6.0.5 on 2026-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_products', '0008_vendorrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='activation_token',
            field=models.CharField(blank=True, help_text='Token unik untuk setup akun vendor setelah pengajuan disetujui', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='token_created_at',
            field=models.DateTimeField(blank=True, help_text='Waktu token aktivasi dibuat', null=True),
        ),
    ]
