# Generated by Django 6.0.3 on 2026-06-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_products', '0009_vendorrequest_activation_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Status percakapan chat', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu percakapan dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Waktu percakapan terakhir diperbarui')),
                ('brand', models.ForeignKey(help_text='Toko/brand yang menjadi lawan bicara', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='master_products.brand')),
                ('customer', models.ForeignKey(help_text='Customer yang memulai percakapan', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Konten pesan chat')),
                ('is_read', models.BooleanField(default=False, help_text='Tandai jika pesan sudah dibaca oleh penerima')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu pesan dibuat')),
                ('sender', models.ForeignKey(help_text='Pengguna yang mengirim pesan', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='Ruang chat yang memuat pesan ini', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='master_products.chatroom')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['customer'], name='chat_rooms_custome_555690_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['brand'], name='chat_rooms_brand_i_6c34cb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['updated_at'], name='chat_rooms_updated_ef325e_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('customer', 'brand'), name='unique_customer_brand_chatroom'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room'], name='chat_messag_room_id_b8fe31_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='chat_messag_sender__e8b05b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_messag_created_eb4133_idx'),
        ),
    ]
