# Generated by Django 6.0.6 on 2026-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, help_text='Kota/Kabupaten', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_postal_code',
            field=models.CharField(blank=True, help_text='Kode pos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_province',
            field=models.CharField(blank=True, help_text='Provinsi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_street',
            field=models.TextField(blank=True, help_text='Jalan dan nomor rumah', null=True),
        ),
    ]
