# Generated by Django 6.0.5 on 2026-05-25 06:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Nama unik dari brand/toko', max_length=255, unique=True)),
                ('nib_or_ktp', models.CharField(help_text='Nomor Induk Berusaha (NIB) atau Nomor KTP untuk verifikasi', max_length=50, unique=True)),
                ('rating', models.FloatField(default=0.0, help_text='Rating brand dari customer (0.0 - 5.0)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('SUSPENDED', 'Ditangguhkan')], default='PENDING', help_text='Status persetujuan brand oleh admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal pendaftaran brand')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal pembaruan terakhir')),
                ('user', models.OneToOneField(help_text='Pemilik/Admin dari brand ini', on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand Profile',
                'verbose_name_plural': 'Brand Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='master_bran_status_ddaf09_idx'), models.Index(fields=['user'], name='master_bran_user_id_c4e4b1_idx')],
            },
        ),
    ]
